[package]
name = "rust-image-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }

[lib]
crate-type = ["cdylib", "rlib"]